export const teams = [
    {
        "id": 1,
        "name": "Manchester City",
        "logo": "https://upload.wikimedia.org/wikipedia/pt/0/02/Manchester_City_Football_Club.png",
        "country": "ENG",
    },
    {
        "id": 2,
        "name": "FC Bayern München",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/140x140/50037.png",
        "country": "GER",
    },
    {
        "id": 3,
        "name": "Real Madrid C.F.",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50051.png",
        "country": "ESP",
    },
    {
        "id": 4,
        "name": "Paris Saint-Germain",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/52747.png",
        "country": "FRA",
    },
    {
        "id": 5,
        "name": "Liverpool FC",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/7889.png",
        "country": "ENG",
    },
    {
        "id": 6,
        "name": "FC Internazionale Milano",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50138.png",
        "country": "ITA",
    },
    {
        "id": 7,
        "name": "Borussia Dortmund",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/52758.png",
        "country": "GER",
    },
    {
        "id": 8,
        "name": "RB Leipzig",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/2603790.png",
        "country": "GER",
    },
    {
        "id": 9,
        "name": "FC Barcelona",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50080.png",
        "country": "ESP",
    },
    {
        "id": 10,
        "name": "Bayer 04 Leverkusen",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50109.png",
        "country": "GER",
    },
    {
        "id": 11,
        "name": "Atlético de Madrid",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50124.png",
        "country": "ESP",
    },
    {
        "id": 12,
        "name": "Atalanta BC",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/52816.png",
        "country": "ITA",
    },
    {
        "id": 13,
        "name": "Juventus",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50139.png",
        "country": "ITA",
    },
    {
        "id": 14,
        "name": "SL Benfica",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50147.png",
        "country": "POR",
    },
    {
        "id": 15,
        "name": "Arsenal FC",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/52280.png",
        "country": "ENG",
    },
    {
        "id": 16,
        "name": "Club Brugge KV",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50043.png",
        "country": "BEL",
    },
    {
        "id": 17,
        "name": "FC Shakhtar Donetsk",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/52707.png",
        "country": "UKR",
    },
    {
        "id": 18,
        "name": "AC Milan",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50058.png",
        "country": "ITA",
    },
    {
        "id": 19,
        "name": "Feyenoord",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/52749.png",
        "country": "NED",
    },
    {
        "id": 20,
        "name": "Sporting CP",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50149.png",
        "country": "POR",
    },
    {
        "id": 21,
        "name": "PSV Eindhoven",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50062.png",
        "country": "NED",
    },
    {
        "id": 22,
        "name": "GNK Dinamo",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50164.png",
        "country": "CRO",
    },
    {
        "id": 23,
        "name": "FC Salzburg",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50030.png",
        "country": "AUT",
    },
    {
        "id": 24,
        "name": "LOSC Lille",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/75797.png",
        "country": "FRA",
    },
    {
        "id": 25,
        "name": "FK Crvena Zvezda",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50069.png",
        "country": "SRB",
    },
    {
        "id": 26,
        "name": "BSC Young Boys",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50031.png",
        "country": "SUI",
    },
    {
        "id": 27,
        "name": "Celtic FC",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50050.png",
        "country": "SCO",
    },
    {
        "id": 28,
        "name": "ŠK Slovan Bratislava",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/52797.png",
        "country": "SVK",
    },
    {
        "id": 29,
        "name": "AS Monaco",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50023.png",
        "country": "FRA",
    },
    {
        "id": 30,
        "name": "AC Sparta Praha",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50033.png",
        "country": "CZE",
    },
    {
        "id": 31,
        "name": "Aston Villa FC",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/52683.png",
        "country": "ENG",
    },
    {
        "id": 32,
        "name": "Bologna FC 1909",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/52969.png",
        "country": "ITA",
    },
    {
        "id": 33,
        "name": "Girona FC",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/2602798.png",
        "country": "ESP",
    },
    {
        "id": 34,
        "name": "VfB Stuttgart",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50107.png",
        "country": "GER",
    },
    {
        "id": 35,
        "name": "SK Sturm Graz",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/50111.png",
        "country": "AUT",
    },
    {
        "id": 36,
        "name": "Stade Brestois 29",
        "logo": "https://img.uefa.com/imgml/TP/teams/logos/50x50/2601306.png",
        "country": "FRA",
    },
]