export const pots = [
    [
        { "id": 0, "name": "AS Roma", "country": "it", },
        { "id": 1, "name": "Man United", "country": "gb-eng", },
        { "id": 2, "name": "FC Porto", "country": "pt", },
        { "id": 3, "name": "Ajax", "country": "nl", },
        { "id": 4, "name": "Rangers", "country": "gb-sct", },
        { "id": 5, "name": "Eintracht Frankfurt", "country": "de", },
        { "id": 6, "name": "Lazio", "country": "it", },
        { "id": 7, "name": "Tottenham", "country": "gb-eng", },
        { "id": 8, "name": "Slavia Praha", "country": "cz", },
    ],
    [
        { "id": 9, "name": "Real Sociedad", "country": "es", },
        { "id": 10, "name": "AZ Alkmaar", "country": "nl", },
        { "id": 11, "name": "Braga", "country": "pt", },
        { "id": 12, "name": "Olympiacos", "country": "gr", },
        { "id": 13, "name": "Lyon", "country": "fr", },
        { "id": 14, "name": "Paok", "country": "gr", },
        { "id": 15, "name": "Fenerbahçe", "country": "tr", },
        { "id": 16, "name": "Maccabi Tel-Aviv", "country": "il", },
        { "id": 17, "name": "Ferencvárosi", "country": "hu", },
    ],
    [
        { "id": 18, "name": "Qarabağ", "country": "az", },
        { "id": 19, "name": "Galatasaray", "country": "tr", },
        { "id": 20, "name": "Viktoria Plzeň", "country": "cz", },
        { "id": 21, "name": "Bodø/Glimt", "country": "no", },
        { "id": 22, "name": "Union Saint-Gilloise", "country": "be", },
        { "id": 23, "name": "Dynamo Kyiv", "country": "ua", },
        { "id": 24, "name": "Ludogorets", "country": "bg", },
        { "id": 25, "name": "Midtjylland", "country": "dk", },
        { "id": 26, "name": "Malmö", "country": "se", },
    ],
    [
        { "id": 27, "name": "Athletic Club", "country": "es", },
        { "id": 28, "name": "Hoffenheim", "country": "de", },
        { "id": 29, "name": "Nice", "country": "fr", },
        { "id": 30, "name": "Anderlecht", "country": "be", },
        { "id": 31, "name": "Twente", "country": "nl", },
        { "id": 32, "name": "Beşiktaş", "country": "tr", },
        { "id": 33, "name": "FCSB", "country": "ro", },
        { "id": 34, "name": "FC RFS", "country": "lv", },
        { "id": 35, "name": "Elfsborg", "country": "se", },
    ]
]