export const pots = [
    [
        { "id": 0, "name": "Man City", "country": "gb-eng", },
        { "id": 1, "name": "Sevilla", "country": "es", }, 
        { "id": 2, "name": "FC Barcelona", "country": "es", },
        { "id": 3, "name": "Napoli", "country": "it", }, 
        { "id": 4, "name": "Bayern München", "country": "de", },
        { "id": 5, "name": "Paris Saint-Germain", "country": "fr", },
        { "id": 6, "name": "SL Benfica", "country": "pt", },
        { "id": 7, "name": "Feyenoord", "country": "nl", },
    ],
    [
        { "id": 8, "name": "Real Madrid", "country": "es", },
        { "id": 9, "name": "Man United", "country": "gb-eng", }, 
        { "id": 10, "name": "Internazionale Milano", "country": "it", },
        { "id": 11, "name": "Borussia Dortmund", "country": "de", },
        { "id": 12, "name": "Atlético de Madrid", "country": "es", },
        { "id": 13, "name": "RB Leipzig", "country": "de", }, 
        { "id": 14, "name": "FC Porto", "country": "pt", }, 
        { "id": 15, "name": "Arsenal", "country": "gb-eng", },
    ],
    [
        { "id": 16, "name": "Shakhtar Donetsk", "country": "ua", }, 
        { "id": 17, "name": "FC Salzburg", "country": "at", }, 
        { "id": 18, "name": "AC Milan", "country": "it", },
        { "id": 19, "name": "Braga", "country": "pt", },
        { "id": 20, "name": "PSV Eindhoven", "country": "nl", },
        { "id": 21, "name": "Lazio", "country": "it", }, 
        { "id": 22, "name": "Crvena Zvezda", "country": "rs", },
        { "id": 23, "name": "København", "country": "dk", }, 
    ],
    [
        { "id": 24, "name": "Young Boys", "country": "ch", }, 
        { "id": 25, "name": "Real Sociedad", "country": "es", }, 
        { "id": 26, "name": "Galatasaray", "country": "tr", }, 
        { "id": 27, "name": "Celtic", "country": "gb-sct", }, 
        { "id": 28, "name": "New Castle", "country": "gb-eng", }, 
        { "id": 29, "name": "Union Berlin", "country": "de", }, 
        { "id": 30, "name": "Antwerp", "country": "be", }, 
        { "id": 31, "name": "Lens", "country": "fr", }, 
    ]
]